---
antiAffinity: "soft"
 
esJavaOpts: "-Xmx512m -Xms512m"
 
resources:
  requests:
    cpu: "100m"
    memory: "512M"
  limits:
    cpu: "1000m"
    memory: "1024M"
 
volumeClaimTemplate:
  accessModes: [ "ReadWriteOnce" ]
  storageClassName: "microk8s-hostpath"
  resources:
    requests:
      storage: 20M
